### ISSUE TITLE
i get some confuse

### ISSUE THREAD

**Issue by JK-chance** [tjddus9597/R-Adapter-ECCV2024#1]
dear sir:
in your define "class StochasticAdapter(nn.Module): "    i saw  the

> if embed_dim < r:
            self.d = nn.Linear(embed_dim, r, bias=bias)
            self.u = nn.Linear(r, embed_dim, bias=bias)
            nn.init.xavier_uniform_(self.d.weight)
            nn.init.zeros_(self.u.weight)
            if bias:
                nn.init.zeros_(self.d.bias)
                nn.init.zeros_(self.u.bias)
        else:
            self.f = nn.Linear(embed_dim, embed_dim, bias=bias)
            nn.init.zeros_(self.f.weight)
            if bias:
                nn.init.zeros_(self.f.bias)

but in the "def Rep_AdaptWeight(model, args, eval_scale=0.5):"  i find  the  

> if adapter_attn.embed_dim > adapter_attn.r:
                merged_weight, _ = reparameterize(adapter_attn.d.weight.squeeze().T, adapter_attn.u.weight.squeeze().T)
                adapt_attn_weight, adapt_attn_bias = reparameterize(merged_weight.squeeze().T, scale=adapt_attn_scale, do_residual=True)
            else:
                adapt_attn_weight, adapt_attn_bias = reparameterize(adapter_attn.f.weight.squeeze().T, scale=adapt_attn_scale, do_residual=True)
            rep_attn_weight, rep_attn_bias = reparameterize(_.attn.out_proj.weight.T, adapt_attn_weight.T, _.attn.out_proj.bias, adapt_attn_bias)

which cause the 

> [rank0]: Traceback (most recent call last):
[rank0]:   File "/home/iot/shared_pool_data3/shared_pool_data3/anaconda3/envs/openclip/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/iot/shared_pool_data3/shared_pool_data3/anaconda3/envs/openclip/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/work/shard_pool_data5/R-Adapter-ECCV2024-master/src/main.py", line 359, in <module>
[rank0]:     main(args)
[rank0]:   File "/work/shard_pool_data5/R-Adapter-ECCV2024-master/src/main.py", line 196, in main
[rank0]:     adapt_utils.Rep_AdaptWeight(model.module.model, args)
[rank0]:   File "/work/shard_pool_data5/R-Adapter-ECCV2024-master/clip/loralib/utils.py", line 124, in Rep_AdaptWeight
[rank0]:     merged_weight, _ = reparameterize(adapter_attn.d.weight.squeeze().T, adapter_attn.u.weight.squeeze().T)
[rank0]:   File "/home/iot/shared_pool_data3/shared_pool_data3/anaconda3/envs/openclip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: 'StochasticAdapter' object has no attribute 'd'`  

in the  val epoch 
If it's really a bug or some other special setting, please let me know,Very much looking forward to your reply!

**Comment by sung-yeon-kim** [comment]
Thanks for letting me know about this issue! 
As I reformulated the code, I might not have checked about the Re-parameterization part to handle rank, r=1.
I will check and debug this issue and commit the new code. Thanks again!

**Comment by JK-chance** [comment]
> Thanks for letting me know about this issue! As I reformulated the code, I might not have checked about the Re-parameterization part to handle rank, r=1. I will check and debug this issue and commit the new code. Thanks again!

Thank you for your prompt response，please let me know once the update is done！
